services:
  web:
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile
    environment:
      - OLLAMA_HOST=host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 boycott_platform.asgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - redis
    env_file:
      - ../../.env
    volumes:
      - ../../:/app
    networks:
      - boycott_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 4G  # Увеличиваем лимит памяти
        reservations:
          memory: 2G

  celery:
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile
    environment:
      - OLLAMA_HOST=host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: celery -A boycott_platform worker -l info
    depends_on:
      - redis
      - postgres_db
    env_file:
      - ../../.env
    volumes:
      - ../../:/app
    networks:
      - boycott_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres_db:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - boycott_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - boycott_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
  redis_data:

networks:
  boycott_network:
    driver: bridge